### ISSUE TITLE
Start from first point of line.

### ISSUE THREAD

**Issue by denny123** [openplans/Leaflet.AnimatedMarker#26]
Why not starting from first point of line?

**Comment by barisaydinoglu** [comment]
Here is my workaround for this issue:
```javascript
var animMarker = L.animatedMarker(routeLine.getLatLngs(), {
	icon: "icon.png",
	autoStart: false
}).on("add", function(){
	window.setTimeout(function(){
		animMarker.start();
	}, 100);
});
```

**Comment by denny123** [comment]
Not working, after start marker set to the second point on line. And not starting animate from first point.

**Comment by gkumar7** [comment]
Here is a fix for the issue. Hope this helps!
https://github.com/openplans/Leaflet.AnimatedMarker/pull/34

**Comment by denny123** [comment]
its working, thank you.
