### ISSUE TITLE
stop moving map when marker is moving

### ISSUE THREAD

**Issue by devidatta** [openplans/Leaflet.AnimatedMarker#30]
hello
i am using leaflet in my project. for moving the markers on the map i am using this plugin. it is very useful for me also. but i am getting a serious problem with it. on my map several vehicles are there on different different positions(gps locations).i am getting new positions(data) via web socket. so while one vehicle is moving and suddenly another vehicle started to move the map immidietely moves to that position.i want wherever the marker may move but the map should always be stand and still. can this be done in anyway? i am really in trouble for this. please help me as soon as possible.for me its very urgent. thanks in advance. any kind of help is welcome.

with regards
datta

**Comment by stahlmanDesign** [comment]
Somewhere in your code you probably need to disable or prevent panTo(); when a marker animates. Or you could try to see if the code is using map.setView([lat,lng], zoom) and force it to stay in place.

There are also some methods to prevent the user moving the map:

// Disable drag and zoom handlers.
map.dragging.disable();
map.touchZoom.disable();
map.doubleClickZoom.disable();
map.scrollWheelZoom.disable();

// Disable tap handler, if present.
if (map.tap) map.tap.disable();
