### ISSUE TITLE
Add git tag

### ISSUE THREAD

**Issue by kennynaoh** [openplans/Leaflet.AnimatedMarker#41]
Hello @atogle ,
I am the member of the [cdnjs](https://github.com/cdnjs/cdnjs) project.
We want to host this library.
Could you add the git tags in Github?
Thanks.

https://github.com/cdnjs/cdnjs/issues/6746

**Comment by atogle** [comment]
Done: https://github.com/openplans/Leaflet.AnimatedMarker/releases/tag/v1.0.0

**Comment by kennynaoh** [comment]
Thanks @atogle
