### ISSUE TITLE
Using with react-leaflet

### ISSUE THREAD

**Issue by jakehm** [openplans/Leaflet.AnimatedMarker#45]
Instead of putting it in my html, I require the plugin like this
`require('./AnimatedMarker')
`
And I add this to the end of AnimatedMarker.js
`module.exports = L.animatedMarker`

My custom element looks like this:
```
require('./AnimatedMarker')
import { MapComponent } from 'react-leaflet'
import L from 'leaflet'

export default class AnimatedMarkerElement extends MapComponent {

  componentWillReceiveProps(nextProps) {
    const line = L.polyline([nextProps.route.coordinates]),
      animatedMarker = L.animatedMarker(line.getLatLngs())

    console.log('in componentWillRecieveProps')
    nextProps.map.addLayer(animatedMarker)
  }

  render() {
    return null
  }
}
```

The error is: 
`Uncaught TypeError: Cannot read property 'lat' of null
`
I think that the plugin is looking for a map that it can't find because its burried inside react elements.

**Comment by jakehm** [comment]
Do you need the map object to be a global object for this plugin to work?

**Comment by jakehm** [comment]
`const line = L.polyline([nextProps.route.coordinates]),` should not be in brackets because it is already an array.

**Comment by swim1986** [comment]
@jakehm Hi, jake, how can I get `this.refs.map.leafletElement` Object
